version: '3.8'
services:
  portfolio:
    build: .
    image: portfolio
    container_name: portfolio
    restart: unless-stopped
    networks:
      - caddy_network # Correct network name

networks:
  caddy_network:
    external: true