version: '3.8'
services:
  portfolio:
    build: .
    image: portfolio
    container_name: portfolio
    restart: unless-stopped
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true

volumes:
  caddy_data:
  caddy_config:
